version: '3.8'

services:
  evolution-api:
    image: atendeti/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - evolution-api:/evolution/instances
    networks:
      - app-network

  n8n:
    image: n8n/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-secret-key}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  evolution-api:
  n8n_data:
